sudo: false

language: java

jdk: oraclejdk8

script:
  - export TERM=dumb
  - ./Src/java/gradlew --version
  - ./Src/java/gradlew --no-daemon -b ./Src/java/build.gradle check

branches:
  only:
    - master

notifications:
  slack: hl7-cql:kmUdP2WczGxC8N4XQ9ew7cd2
